apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-limit-range
spec:
  limits:
  - type: Container
    max:
      cpu: "500m"
    min:
      cpu: "100m" 
    default:
      cpu: "200m"
    defaultRequest:
      cpu: "150m"