apiVersion: v1
kind: LimitRange
metadata:
  name: memory-limit-range
spec:
  limits:
  - type: Container
    max:
      memory: "256Mi"
    min:
      memory: "64Mi"
    default:
      memory: "128Mi"
    defaultRequest:
      memory: "64Mi"