apiVersion: v1
kind: Pod
metadata:
  name: my-custom-scheduler-pod
  namespace: kube-system
spec:
  containers:
    
    - command:
        - kube-scheduler
        - --address=127.0.0.1
        - --kubeconfig=/etc/kubernetes/scheduler.conf
        - --config=/etc/kubernetes/scheduler-config.yaml
      name: kube-scheduler
      image: k8s.gcr.io/kube-scheduler:v1.27.3