# yaml-language-server: disable
apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
profiles:
  - schedulerName: my-scheduler
leadershipElection:
  leaderElect: true
  resourceName: lock-obj-my-scheduler
  resourceNamespace: kube-system